apiVersion: v1
kind: Service
metadata:
  name: dabom-svc
  namespace: dabom
spec:
  selector:
    type: backend
    ver: \$NEW_VER # blue/green
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP