kind: Service
apiVersion: v1
metadata:
  name: dabom-front
  namespace: dabom
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32116
  selector:
    type: app
    ver: green
  type: LoadBalancer